### ISSUE TITLE
建议直接写一个本地mod拦截客户端数据包来实现服务器无需安装ysm也可以使用本地模型的能力（

### ISSUE THREAD

**Issue by Anjiurine** [Era4FunMC/MyYsmNonFull#3]

**Comment by MrHua269** [comment]
emmm,ysm本体的class都混淆了，虽然可以实现，但是部分版本的ysm混淆用的mapping不一样，我没有那么多功夫去deobf其他版本的ysm然后维护多个版本，如果ysm后面没混淆(估计不太可能)我会考虑单独魔改ysm的()

**Comment by Anjiurine** [comment]
> emmm,ysm本体的class都混淆了，虽然可以实现，但是部分版本的ysm混淆用的mapping不一样，我没有那么多功夫去deobf其他版本的ysm然后维护多个版本，如果ysm后面没混淆(估计不太可能)我会考虑单独魔改ysm的()

可以尝试直接抓包然后分析ysm的数据包吗（不是很了解

**Comment by MrHua269** [comment]
> > emmm,ysm本体的class都混淆了，虽然可以实现，但是部分版本的ysm混淆用的mapping不一样，我没有那么多功夫去deobf其他版本的ysm然后维护多个版本，如果ysm后面没混淆(估计不太可能)我会考虑单独魔改ysm的()
> 
> 可以尝试直接抓包然后分析ysm的数据包吗（
> 对这方面不是很了解（

emmm，我暑假八月份deobf过一次，虽然不是很全，这个插件就是deobf之后一遍扒混淆和deobf了的一边对着着写的，它的通信走的fabricapi给的那个(实际上就是走的mc的custompayload)，如果你要想用最粗暴的方法的话可以在客户端发来缓存列表之后再全部按照他发来的md5用缓存命中的数据包发回去，具体你可以康康这个插件的源码()

**Comment by Anjiurine** [comment]
> > > emmm,ysm本体的class都混淆了，虽然可以实现，但是部分版本的ysm混淆用的mapping不一样，我没有那么多功夫去deobf其他版本的ysm然后维护多个版本，如果ysm后面没混淆(估计不太可能)我会考虑单独魔改ysm的()
> > 
> > 
> > 可以尝试直接抓包然后分析ysm的数据包吗（
> > 对这方面不是很了解（
> 
> emmm，我暑假八月份deobf过一次，虽然不是很全，这个插件就是deobf之后一遍扒混淆和deobf了的一边对着着写的，它的通信走的fabricapi给的那个(实际上就是走的mc的custompayload)，如果你要想用最粗暴的方法的话可以在客户端发来缓存列表之后再全部按照他发来的md5用缓存命中的数据包发回去，具体你可以康康这个插件的源码()(forge版本也一样只不过有个数据包多了个uuid要写入到buffer里)

主要是我不是研究java的，主要在前端那边，所以看到了这个项目才觉得有一线生机（

**Comment by Anjiurine** [comment]
看到你跟我是同龄人，一下差距就拉大了（

**Comment by MrHua269** [comment]
> 看到你跟我是同龄人，一下差距就拉大了（

az，其实我也就初学，有的东西还是东拼西凑来的(()
